version: "3"  # 
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - "7071:27017"
    volumes:
      - ./db:/data/db

  node:
    depends_on:
      - mongodb
    build:
      context: ./node_app
      dockerfile: node.Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "6868:8080"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./node_app:/code
    command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing