# version of docker compose to use
version: "3"

# the services that will build
services:
  app: # name of the service
    build:
      context: . # current directory
    ports:
      - "8000:8000"
    # the volume allows to get updates that we make to our project
    # into docker image in real-time
    volumes:
      - ./app:/app # maps ./app from root to /app on image
    command: > # " > = next line continue "
      sh - c "python manage.py run server 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=changethis
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changethis